# Generated by Django 4.2.16 on 2024-10-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20)),
                ('move', models.CharField(max_length=20)),
                ('total_connection', models.IntegerField()),
                ('create_user', models.CharField(max_length=50)),
                ('_user', models.CharField(max_length=50)),
            ],
        ),
    ]
