# Generated by Django 4.2.16 on 2024-10-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tictactoe',
            old_name='_user',
            new_name='join_user',
        ),
    ]
